<a href="https://colab.research.google.com/github/DimDragg/-/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Чуркін Дмитро, був присутній на конференції, варіант 13, ФІТ 2-15

In [26]:
import numpy as np
a = np.array([
   		 [1, -4, -5],
   		 [2, -3, 1],
   		 [1, 4, 2],
])
b = np.array([[-5], [-7], [-1]])


In [27]:
#Матричний метод (1 спосіб)
det_a = np.linalg.det(a)
if det_a == 0:
    print("Визначник дорівнює нулю - рішень немає")
else:
    a_inv = np.linalg.inv(a)
    print(f"Обернена матриця до матриці A: \r\n {a_inv }")
    print(f"Вектор рішення: \r\n {a_inv.dot(b)}")

Обернена матриця до матриці A: 
 [[ 0.18867925  0.22641509  0.35849057]
 [ 0.05660377 -0.13207547  0.20754717]
 [-0.20754717  0.1509434  -0.09433962]]
Вектор рішення: 
 [[-2.88679245]
 [ 0.43396226]
 [ 0.0754717 ]]


In [ ]:
import numpy as np

def solve_inv_matrix(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose:
        print(f"Визначник матриці A: {round(det, 2)}")

    if det == 0:
        print("Визначник дорівнює нулю — система не має єдиного розв’язку.")
        return None

    a_inv = np.linalg.inv(a)
    if verbose:
        print(f"Обернена матриця до матриці A:\n{a_inv}")

    x = a_inv.dot(b)
    if verbose:
        print(f"Вектор розв’язку:\n{x}")
    return x

# Тестовий приклад:
a = np.array([[2, 1], [5, 3]])
b = np.array([3, 7])
print(f"Вектор рішення:\n{solve_inv_matrix(a, b, verbose=True)}")

Визначник матриці A: 1.0
Обернена матриця до матриці A:
[[ 3. -1.]
 [-5.  2.]]
Вектор розв’язку:
[ 2. -1.]
Вектор рішення:
[ 2. -1.]


In [28]:
# Напиши функцію для вирішення системи методом Крамера
import numpy as np

def solve_cramer(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose:
        print(f"Визначник матриці A: {round(det, 2)}")
    if det == 0:
        print("Визначник дорівнює нулю — система не має єдиного розв’язку.")
        return None

    n = len(a)
    b = b.reshape(-1, 1)  # гарантуємо, що b — стовпець
    x = np.zeros(n)

    for i in range(n):
        temp = np.copy(a)
        temp[:, i] = b[:, 0]
        det_temp = np.linalg.det(temp)
        x[i] = det_temp / det
        if verbose:
            print(f"Матриця A з заміненим стовпцем {i+1}:\n{temp}")
            print(f"Визначник цієї матриці: {round(det_temp, 2)}\n")

    return x

# Приклад використання:
a = np.array([[2, 1], [5, 3]])
b = np.array([3, 7])
print(f"Вектор рішення:\n{solve_cramer(a, b, verbose=True)}")

Визначник матриці A: 1.0
Матриця A з заміненим стовпцем 1:
[[3 1]
 [7 3]]
Визначник цієї матриці: 2.0

Матриця A з заміненим стовпцем 2:
[[2 3]
 [5 7]]
Визначник цієї матриці: -1.0

Вектор рішення:
[ 2. -1.]


In [29]:
x = np.linalg.solve(a, b)

print(x)

[ 2. -1.]


In [30]:
import numpy as np

def solve_gauss(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose:
        print(f"Визначник матриці A: {round(det, 2)}")
    if det == 0:
        print("Визначник дорівнює нулю — система не має єдиного розв’язку.")
        return None

    n = len(b)
    m = np.hstack((a.astype(float), b.reshape(-1, 1).astype(float)))

    # Прямий хід методу Гауса-Жордана
    for i in range(n):
        # Пошук головного елемента
        if m[i, i] == 0:
            for k in range(i + 1, n):
                if m[k, i] != 0:
                    m[[i, k]] = m[[k, i]]
                    break

        # Робимо провідний елемент рівним 1
        m[i] = m[i] / m[i, i]

        # Занулення інших елементів у стовпці
        for j in range(n):
            if i != j:
                ratio = m[j, i]
                m[j] = m[j] - ratio * m[i]

        if verbose:
            print(f"Крок {i+1}:\n{m}\n")

    return m[:, -1]

# Приклад використання:
a = np.array([[2, 1], [5, 3]])
b = np.array([3, 7])
print(f"Вектор рішення:\n{solve_gauss(a, b, verbose=True)}")

Визначник матриці A: 1.0
Крок 1:
[[ 1.   0.5  1.5]
 [ 0.   0.5 -0.5]]

Крок 2:
[[ 1.  0.  2.]
 [ 0.  1. -1.]]

Вектор рішення:
[ 2. -1.]
