<a href="https://colab.research.google.com/github/DimDragg/-/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_%D0%92%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F_%D0%95%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B8_%D0%BB%D1%96%D0%BD%D1%96%D0%B9%D0%BD%D0%BE%D1%97_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8_%D0%A7%D1%83%D1%80%D0%BA%D1%96%D0%BD_%D0%A4%D0%86%D0%A2_3_15_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 1
Вступ до машинного навчання. Елементи лінійної алгебри.
Чуркін ФІТ 3-15 номер 15

Був присутній на парі

Завдання 1.
Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та виведіть його значення.

In [5]:
import numpy as np

primes = []
for num in range(2, 71):
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        primes.append(num)

primes_array = np.array(primes)
print("Завдання 1:")
print(primes_array)

Завдання 1:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67]


Завдання 2
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів перших натуральних чисел.

In [4]:
squares = np.array([i**2 for i in range(1, 10)]).reshape(3, 3)
print("\nЗавдання 2:")
print(squares)


Завдання 2:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Завдання 3
Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть максимальний елемент.

In [6]:
array_5x5 = np.random.randint(-10, 11, size=(5, 5))
max_element = np.max(array_5x5)

print("\nЗавдання 3:")
print(array_5x5)
print("Максимальний елемент:", max_element)


Завдання 3:
[[  1   6  -4   8  -7]
 [-10  -1  -1   7  -1]
 [ -3   5  -9   0   2]
 [  5   3  -1   4   9]
 [ -2  -5   6   1  -4]]
Максимальний елемент: 9


Завдання 4
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в кожному стовпці.

In [8]:
array_4x4 = np.random.rand(4, 4)
max_per_column = np.max(array_4x4, axis=0)

print("\nЗавдання 4:")
print(array_4x4)
print("Вектор-рядок з максимальними елементами кожного стовпця:")
print(max_per_column)


Завдання 4:
[[0.93041488 0.51936875 0.09833713 0.21637278]
 [0.27597345 0.66450444 0.8821539  0.24658965]
 [0.80062914 0.36472605 0.96333353 0.64324288]
 [0.22951691 0.14547623 0.1693586  0.76967118]]
Вектор-рядок з максимальними елементами кожного стовпця:
[0.93041488 0.66450444 0.96333353 0.76967118]


Завдання 5 Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [9]:
a = np.random.randint(-10, 11, 7)
b = np.random.randint(-10, 11, 7)

sum_array = a + b
diff_array = a - b
prod_array = a * b

print("\nЗавдання 5:")
print("Масив a:", a)
print("Масив b:", b)
print("Додавання:", sum_array)
print("Віднімання:", diff_array)
print("Множення:", prod_array)


Завдання 5:
Масив a: [ 2 10  0  6  2  2  6]
Масив b: [-3 -2 -4 -3  2  2 -6]
Додавання: [-1  8 -4  3  4  4  0]
Віднімання: [ 5 12  4  9  0  0 12]
Множення: [ -6 -20   0 -18   4   4 -36]


Завдання 6 Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та знайдіть їх добуток.

In [10]:
A = np.random.randint(-10, 11, (4, 4))
B = np.random.randint(-10, 11, (4, 4))
product_6 = np.dot(A, B)

print("Завдання 6:")
print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Добуток A * B:\n", product_6)

Завдання 6:
Матриця A:
 [[ 7 -3  2 -4]
 [-2 -1  7  9]
 [ 1 -3  8  7]
 [-5  5 10  6]]
Матриця B:
 [[-5  8  1 -9]
 [ 4 -8 -3 10]
 [-3  5  0  2]
 [-2  4 -1 -7]]
Добуток A * B:
 [[-45  74  20 -61]
 [-33  63  -8 -41]
 [-55 100   3 -72]
 [  3  -6 -26  73]]


Завдання 7 Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.

In [11]:
C = np.random.randint(1, 4, (4, 2))
D = np.random.randint(1, 4, (2, 2))
product_7 = np.dot(C, D)

print("\nЗавдання 7:")
print("Матриця C:\n", C)
print("Матриця D:\n", D)
print("Добуток C * D:\n", product_7)


Завдання 7:
Матриця C:
 [[1 2]
 [3 1]
 [2 1]
 [1 3]]
Матриця D:
 [[3 2]
 [2 3]]
Добуток C * D:
 [[ 7  8]
 [11  9]
 [ 8  7]
 [ 9 11]]


Завдання 8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [12]:
while True:
    E = np.random.randint(1, 8, (2, 2))
    if np.linalg.det(E) != 0:  # перевірка
        break

inverse_E = np.linalg.inv(E)

print("\nЗавдання 8:")
print("Матриця E:\n", E)
print("Обернена матриця E^-1:\n", inverse_E)


Завдання 8:
Матриця E:
 [[7 6]
 [2 4]]
Обернена матриця E^-1:
 [[ 0.25   -0.375 ]
 [-0.125   0.4375]]


Завдання 9. Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [13]:
F = np.random.randint(0, 2, (3, 5))
transpose_F = F.T

print("\nЗавдання 9:")
print("Матриця F:\n", F)
print("Транспонована матриця F^T:\n", transpose_F)


Завдання 9:
Матриця F:
 [[1 0 1 0 0]
 [1 1 1 1 0]
 [0 0 1 0 1]]
Транспонована матриця F^T:
 [[1 1 0]
 [0 1 0]
 [1 1 1]
 [0 1 0]
 [0 0 1]]


Завдання 10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [14]:
G = np.random.rand(3, 4)
v = np.random.randint(1, 11, (4, 1))
product_10 = np.dot(G, v)

print("\nЗавдання 10:")
print("Матриця G:\n", G)
print("Вектор v:\n", v)
print("Добуток G * v:\n", product_10)


Завдання 10:
Матриця G:
 [[0.68965771 0.60231552 0.7050254  0.73653377]
 [0.70162891 0.28537682 0.71754517 0.35499518]
 [0.07925247 0.34332376 0.65269858 0.23393319]]
Вектор v:
 [[ 5]
 [ 6]
 [ 9]
 [10]]
Добуток G * v:
 [[20.77274789]
 [15.22826382]
 [10.66982399]]


Завдання 11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору.

In [16]:
M = np.random.rand(2, 3)
v = np.random.rand(3, 1)

# Розширення до (1,3)
v_row = v.T

mask = M < v_row
sum_elements = np.sum(M[mask])

print("Завдання 11:")
print("Матриця M:\n", M)
print("Вектор v:\n", v)
print("Сума елементів M, менших за відповідні елементи v:", sum_elements)

Завдання 11:
Матриця M:
 [[0.1175135  0.55487038 0.33427111]
 [0.31713002 0.28452634 0.56876359]]
Вектор v:
 [[0.79701863]
 [0.87086495]
 [0.10298195]]
Сума елементів M, менших за відповідні елементи v: 1.2740402421914063


Завдання 12 Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму

In [17]:
A = np.random.randint(1, 11, (8, 8))
B = np.random.randint(1, 11, (8, 8))
sum_matrix = A + B

print("\nЗавдання 12:")
print("Сума матриць:\n", sum_matrix)


Завдання 12:
Сума матриць:
 [[ 8 11  7 13  7 11  2 11]
 [ 6 11  3 15 18  4  5 10]
 [ 5  7  8 10  7 12 17  9]
 [11  5 14 19 14  6 12 10]
 [10 10 13  7 12 12  6 12]
 [ 3  8 14 15 14 11  8  7]
 [12 15 12  7 12  9  5 12]
 [14 10  7 12 15 17  7  8]]


Завдання 13 Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток їх елементів.

In [18]:
C = np.random.uniform(-1, 1, (3, 3))
D = np.random.uniform(-1, 1, (3, 3))

elementwise_product = C * D

print("\nЗавдання 13:")
print("Добуток елементів матриць:\n", elementwise_product)


Завдання 13:
Добуток елементів матриць:
 [[ 0.16369398 -0.21660155  0.64281832]
 [-0.11061146  0.15793768 -0.51804038]
 [ 0.36912403  0.47040272 -0.21981553]]


Завдання 14 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть добуток елементів матриці, які більше за їх середнє арифметичне значення.

In [19]:
E = np.random.uniform(-5, 5, (3, 3))
mean_E = np.mean(E)

elements_greater = E[E > mean_E]
product_greater = np.prod(elements_greater) if elements_greater.size > 0 else 0

print("\nЗавдання 14:")
print("Матриця E:\n", E)
print("Середнє значення:", mean_E)
print("Добуток елементів більших за середнє:", product_greater)


Завдання 14:
Матриця E:
 [[ 1.92509107  1.19739948 -2.88778165]
 [-0.21543599  4.07075952  0.43953649]
 [-4.17984734 -1.91389245 -3.28044262]]
Середнє значення: -0.5382903880097936
Добуток елементів більших за середнє: -0.8885440796031062


Завдання 15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем ціле значення в кожному рядку матриці.

In [20]:
F = np.random.uniform(-0.5, 0.5, (3, 3))

max_abs_values = F[np.arange(3), np.argmax(np.abs(F), axis=1)]
column_vector = max_abs_values.reshape(3, 1)

print("\nЗавдання 15:")
print("Матриця F:\n", F)
print("Вектор-стовпчик з найбільшими за модулем значеннями:\n", column_vector)


Завдання 15:
Матриця F:
 [[-0.28167933 -0.17098476 -0.40268015]
 [-0.36767038 -0.02760735 -0.17391717]
 [-0.17088663 -0.16561401  0.04850046]]
Вектор-стовпчик з найбільшими за модулем значеннями:
 [[-0.40268015]
 [-0.36767038]
 [-0.17088663]]


**Висновок:**
У ході лабораторної роботи я опрацьовав базові операції з одновимірними та двовимірними масивами, за допомогою бібліотеки NumPy в середовищі Google Colab. Було створено вектори та матриці різних розмірів, виконано їх заповнення випадковими та обчислюваними значеннями, а також реалізовано основні арифметичні й логічні операції над ними.