<a href="https://colab.research.google.com/github/DimDragg/-/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Чуркін Дмитро, був присутній на конференції, варіант 13, ФІТ 2-15

In [16]:
import numpy as np
a = np.array([
   		 [1, -4, -5],
   		 [2, -3, 1],
   		 [1, 4, 2],
])
b = np.array([[-5], [-7], [-1]])


In [17]:
#Матричний метод (1 спосіб)
det_a = np.linalg.det(a)
if det_a == 0:
    print("Визначник дорівнює нулю - рішень немає")
else:
    a_inv = np.linalg.inv(a)
    print(f"Обернена матриця до матриці A: \r\n {a_inv }")
    print(f"Вектор рішення: \r\n {a_inv.dot(b)}")

Обернена матриця до матриці A: 
 [[ 0.18867925  0.22641509  0.35849057]
 [ 0.05660377 -0.13207547  0.20754717]
 [-0.20754717  0.1509434  -0.09433962]]
Вектор рішення: 
 [[-2.88679245]
 [ 0.43396226]
 [ 0.0754717 ]]


In [18]:
# Напиши функцію для вирішення системи матричним методом (2 спосіб)
def solve_inv_matrix(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose: print(f"Визначник матриці A: {round(det)}")
    if det == 0:
      	print("Визначник дорівнює нулю - рішень немає")
        return None

    a_inv= np.linalg.inv(a)
		if verbose: print(f"Обернена матриця до матриці A: \r\n {a_inv }")
		return a_inv.dot(b)

print(f"Вектор рішення: \r\n {solve_inv_matrix(a, b)}")

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-18-1b3173125585>, line 7)

In [19]:
#метод Крамера (1 спосіб)
# Метод Крамера
det_a = np.linalg.det(a)

if det_a == 0:
    print("Визначник дорівнює нулю — система не має єдиного розв’язку.")
else:
    def replace_column(matrix, column_index, new_column):
				new_matrix = np.copy(matrix)
				new_matrix[:, column_index] = new_column
				return new_matrix

    # Обчислюємо Δx, Δy, Δz
    delta_x = np.linalg.det(replace_column(a, 0, b.T))
		delta_y = np.linalg.det(replace_column(a, 1, b.T))
		delta_z = np.linalg.det(replace_column(a, 2, b.T))

		# Обчислюємо x, y, z
		print('x =', delta_x / det_a)
		print('y =', delta_y / det_a)
		print('z =', delta_z / det_a)

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-19-0fefc2f7fe28>, line 9)

In [11]:
# Напиши функцію для вирішення системи методом Крамера
def solve_cramer(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose: print(f"Визначник матриці A: {round(det)}")
    if det == 0:
        print("Визначник дорівнює нулю - рішень немає")
        return None

    len_a = len(a)
    x = np.zeros((len_a, 1))
    for i in range(len_a):
        temp = np.copy(a)
        temp[:, [i]] = b
        x[i, 0] = np.linalg.det(temp)/det

    return x


print(f"Вектор рішення: \r\n {solve_cramer(a, b)}")

Вектор рішення: 
 [[2.]
 [1.]
 [1.]]


In [15]:
x = np.linalg.solve(a, b)

print(x)

[[2.]
 [1.]
 [1.]]


In [21]:
# Напиши функцію для вирішення системи методом Гауса
def solve_gausse(a, b, verbose=False):
    det = np.linalg.det(a)
		if verbose: print(f"Визначник матриці A: {round(det)}")
		if det == 0:
				print("Визначник дорівнює нулю - рішень немає")
				return None
		# Reading number of unknowns
		n = len(b)
		m = np.concatenate([a, b], axis=1, dtype=float)

		# Applying Gauss-Jordan Elimination
		for i in range(n):

		# Swap rows to avoid division by 0
				if m[i, i] == 0:
						for k in range(i+1, n):
								if m[k, k] != 0:
										m[[i, k], :] = m[[k, i], :]
										break


				if m[i, i] != 1:
    				m[i, :] *= 1/m[i, i]

				for j in range(n):
        		if i != j:
								ratio = m[j][i]/m[i][i]

								m[j, :] = m[j, :] - ratio * m[i, :]

		return m[:, [-1]]

print(f"Вектор рішення: \r\n {solve_gausse(a, b)}")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 27)